url: "https://mrshiny608.github.io"
baseurl: "/MrShiny608"
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
  show_excerpts: true
  hide_site_feed_link: true
  social_links:
  - title: LinkedIn
    icon: linkedin
    url: "https://www.linkedin.com/in/timothybrookes/"
  - title: Blog
    icon: github
    url: "https://mrshiny608.github.io/MrShiny608/"